In [1]:
for i in range(8):
    print("Shah G is Back")

Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back


In [3]:
i=0
while i<8:
    print("Shah G is Back")
    i=i+1

Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back
Shah G is Back


In [4]:
def divide(x,y):
    return(x/y)

In [10]:
if i==8:
    print("hi")

hi


In [6]:
a=[1,2,3,4,5,6,7]

In [7]:
a

[1, 2, 3, 4, 5, 6, 7]

In [11]:
import numpy as np

In [12]:
np.array

<function numpy.array>

In [13]:
np.array(10)

array(10)

In [18]:
arr

array(10)

In [15]:
arr

array(10)

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [21]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
import pandas as pd

In [23]:
a3D.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [27]:
pd.read_csv(r'C:\Users\PMLS\Desktop\Untitled Folder\employees_messy.csv')

,Employee_ID,First_Name,Last_Name,Gender,Age,Join_Date,Department,City,Salary_PKR,Phone,Email,Performance_Score,Unnamed: 12
0,EMP 0113,hassan,Qureshi,m,45 yrs,06-13-2022,finance,islamabad,NaN,03323308823,missing,5,NaN
1,EMP 0055,FATIMA,AHMED,f,NaN,03-Jan-20,IT,karachi,PKR 119892,-9122210,FATIMA.AHMED@HOTMAIL.COM,NaN,NaN
2,EMP0158,ahmed,chaudhry,Male,NaN,22-04-20,H.R,rawalpindi,80720,NaN,missing,NaN,NaN
3,emp0136,Ali,chaudhry,female,28,11-20-2022,sales,Rawalpindi,140154,NaN,ali.chaudhry @ gmail.com,5,NaN
4,EMP134,ahmed,Akhtar,M,NaN,06-21-2020,sales,islamabad,NaN,03348959963,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,emp0130,bilal,Khan,M,38,11-07-20,Finance,Islamabad,"148,092",0349-3270167,bilal. khan@outlook. com,NaN,NaN
206,EMP108,bilal,Khan,female,23 yrs,06-20-2020,it,karachi,NaN,0313-8763551,BILAL.KHAN@OUTLOOK.COM,NaN,NaN
207,EMP0095,bilal,AHMED,Male,NaN,02-Jan-23,FINANCE,LAHORE,81728,03222924992,bilal. ahmed@hotmail. com,not rated,NaN
208,EMP 0046,FATIMA,butt,Male,27 yrs,16-02-22,sales,KARACHI,"125,562",NaN,FATIMA.BUTT@GMAIL.COM,not rated,NaN
